global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  # - job_name: 'aspire services'
  #   scrape_interval: 15s
  #   metrics_path: ''    
  #   static_configs:
  #     - targets: ['localhost:9000', 'localhost:9001', 'localhost:9002', 'localhost:9004', 'localhost:9005', 'localhost:9006', 'localhost:9007', 'localhost:9008', 'localhost:9009', 'localhost:9010', 'localhost:9011', 'localhost:9012', 'localhost:9013', 'localhost:9014', 'localhost:9015']
  - job_name: 'Streaming Service'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9000']

  - job_name: 'Known Signal Matcher'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9001']

  - job_name: 'Signal ID Visualization'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9002']
  - job_name: 'Score Aggregation Service'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9003']
  - job_name: 'Measurements'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9004']
  - job_name: 'Template Generator'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9005']
  - job_name: 'Clusterer Service'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9006']
  - job_name: 'Denoising'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9007']
  - job_name: 'Mode Partitioner'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9008']
  - job_name: 'Behavior Modeler'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9009']
  - job_name: 'Firing order Expansion'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9010']
  - job_name: 'EIM Generator'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9011']
  - job_name: 'DW Filtering Service'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9012']
  - job_name: 'Repository to Modes'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9013']
  - job_name: 'Keystone'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9014']
  - job_name: 'Modulation Classifier'
    scrape_interval: 15s
    metrics_path: ''    
    static_configs:
      - targets: ['localhost:9015']