{
 "title": "ASPIRE Metrics Final",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": "label_values(instance)" },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Connections",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "as_connections", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Memory Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "RSS Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_rss", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "VMs Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_vms", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Shared Mem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_shared", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Text Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_text", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Lib Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_lib", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Data Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_data", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Dirty Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_dirty", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "USS Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_uss", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "PSS Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_pss", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "SWAP Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pmem_swap", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "CPU Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Percent",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_cpu_percent", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "User Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_cpu_times_user", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "IO Wait Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_cpu_times_iowait", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "System Child Process Wait Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_cpu_times_children_system", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "System Wait Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_cpu_times_children_system", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Context Switches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Voluntary Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pctxsw_voluntary", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Involuntary Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pctxsw_involuntary", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "CPU (Number of Cores)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Number of Cores",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "as_cpu_num", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "IO Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pio_read_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pio_write_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Read Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pio_read_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Write Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pio_write_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Read Chars",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pio_read_chars", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Write Chars",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_pio_write_chars", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Number of Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "Number of Threads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "as_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "as_open_files", "legendFormat": "{{job}}" }
   ]
  }
 ]
}